// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"tiktok_electric_business/pkg/wego"
	"tiktok_electric_business/sms/grpc"
	"tiktok_electric_business/sms/ioc"
)

// Injectors from wire.go:

func Init() *wego.App {
	logger := ioc.InitLogger()
	smsService := ioc.InitSmsMemoryService(logger)
	smsServiceServer := grpc.NewSmsServiceServer(smsService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGrpcxServer(smsServiceServer, client, logger)
	app := &wego.App{
		GrpcServer: server,
	}
	return app
}
