version: "3"

services:
  mysql8:
    image: mysql:8.0
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --binlog-format=ROW
      - --server-id=1
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./scripts/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306