// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"tiktok_electric_business/pkg/wego"
	"tiktok_electric_business/user/grpc"
	"tiktok_electric_business/user/ioc"
	"tiktok_electric_business/user/repository"
	"tiktok_electric_business/user/repository/cache"
	"tiktok_electric_business/user/repository/dao"
	"tiktok_electric_business/user/service"
)

// Injectors from wire.go:

func Init() *wego.App {
	db := ioc.InitDB()
	userDAO := dao.NewGormUserDAO(db)
	cmdable := ioc.InitRedis()
	userCache := cache.NewRedisUserCache(cmdable)
	logger := ioc.InitLogger()
	userRepository := repository.NewCachedUserRepository(userDAO, userCache, logger)
	limiter := ioc.InitLimiter(cmdable)
	userService := service.NewLimitedUserService(userRepository, logger, limiter)
	userServiceServer := grpc.NewUserServiceServer(userService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGrpcxServer(userServiceServer, client, logger)
	app := &wego.App{
		GrpcServer: server,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitDB, ioc.InitEtcdClient, ioc.InitLimiter, ioc.InitLogger, ioc.InitRedis)
